// This runner is auto-generated by Brittle

runTests()

async function runTests () {
  const test = (await import('brittle')).default

  test.pause()

  await import('./basic.js')
  await import('./merge.js')
  await import('./cmd.js')

  test.resume()
}
